---
sudo: required

services:
  - docker

env:
  global:
    - distribution: docker-stack
    - container_id: docker-stack-container
    - container_user: aiida

before_install:
  - docker build --no-cache --rm --file=Dockerfile --tag=${distribution}:latest .

script:
  - docker run --name ${container_id} -e HEADLESS=True --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${distribution}:latest
  - docker exec --tty --user root "${container_id}" wait-for-services
  - docker exec --tty --user ${container_user} "${container_id}" verdi plugin list aiida.calculations
  - docker exec --tty --user ${container_user} "${container_id}" verdi daemon status

after_script:
  - docker logs ${container_id}
