---
name: aiidalab-docker-stack
channels:
    - conda-forge
dependencies:
    - doit=0.36.0
    - dunamai=1.13.0
    - pip=22.2.2
    - pytest=7.1.2
    - requests==2.28.1
    - pip:
          - docker-compose==1.29.2
          - pytest-docker==1.0.0
          - pytest-selenium==4.0
          - bumpver==2022.1120
