---
# Build and push image to DockerHub

name: release-image

on:
    push:
        branches:
            - master
            - develop
            - refactor-into-stack  # TODO: remove this
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*

jobs:

    build-docker-image:

        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - uses: actions/checkout@v2
            - name: Install Conda environment from environment.yml
              uses: mamba-org/provision-with-micromamba@v12
            - name: Docker meta exta
              id: meta_extra
              run: |
                  echo "::set-output name=tags::$(./build.py tags --github-actions)"
                  echo "::set-output name=build_args::$(./build.py docker-build-args --github-actions)"
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            # - name: Login to DockerHub   # TODO: uncomment this
            #   uses: docker/login-action@v1
            #   with:
            #       username: ${{ secrets.DOCKER_USERNAME }}
            #       password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Docker meta base
              id: meta_base
              uses: docker/metadata-action@v4
              with:
                  images: aiidalab/base
                  tags: |
                      type=ref,event=branch
                      ${{ steps.meta_extra.outputs.tags }}
            - name: Build and push base image
              id: build_base_image
              uses: docker/build-push-action@v3
              with:
                  context: stack/base
                  push: true
                  tags: ${{ steps.meta_base.outputs.tags }}
                  platforms: linux/amd64, linux/arm64
                  build-args: |
                      ${{ steps.meta_extra.outputs.build_args }}
            - name: Docker meta lab
              id: meta_lab
              uses: docker/metadata-action@v4
              with:
                  images: aiidalab/lab
                  tags: |
                      type=ref,event=branch
                      ${{ steps.meta_extra.outputs.tags }}
            - name: Build and push lab image
              uses: docker/build-push-action@v3
              with:
                  context: stack/lab
                  push: true
                  tags: ${{ steps.meta_lab.outputs.tags }}
                  platforms: linux/amd64, linux/arm64
                  build-args: |
                      ${{ steps.meta_extra.outputs.build_args }}
                      BASE_IMAGE=aiidalab/base@${{ steps.build_base_image.outputs.digest }}
